routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'sistema'], function () {
    
    Route::resource('Cliente', 'ClienteController');
    Route::resource('/venta', 'VentaController');
    Route::post('/venta/eliminar','VentaController@eliminar');

    Route::get('/nota/{id}', 'NotaController@nota')->name('venta.nota');
    Route::get('/','SistemaController@index')->name('sistema');
    Route::post('/cliente','ClienteController@showCliente');
    Route::post('/cliente/editar','ClienteController@editar')->name('cliente.editar');
    Route::post('/cliente/eliminar','ClienteController@eliminar');
    Route::resource('inventario','InventarioController');
    Route::post('/showProducto','InventarioController@showProducto');
    Route::resource('servicio','ServicioController');
    Route::post('serviciofolio','ServicioController@buscarFolio');
    Route::post('serviciocliente','ServicioController@buscarCliente');
    Route::get('/recientes/servicio','ServicioController@recientes')->name('servicio.recientes');
    Route::get('/comprobante/{id}','NotaController@comprobante')->name('servicio.comprobante');
    Route::post('/servicio/eliminar','ServicioController@eliminar');
    Route::post('/servicio/terminado','ServicioController@terminado');

    Route::get('/servicios/general','ServicioController@consultaServicioG')->name('servicio.gconsulta');
    Route::get('/servicios/fecha','ServicioController@consultaFecha')->name('servicio.fecha');
    Route::post('/serviciopost/fecha','ServicioController@consultaServicioF')->name('servicio.fconsulta');

    Route::get('/ventas/general','VentaController@consultaVentaG')->name('venta.gconsulta');
    Route::get('/ventas/fecha','VentaController@consultaFecha')->name('venta.fecha');
    Route::post('/ventapost/fecha','VentaController@consultaVentaF')->name('venta.fconsulta');
    
    Route::get('/clientes/fecha','ClienteController@consultaFecha')->name('cliente.fecha');
    Route::post('/clientepost/fecha','ClienteController@consultaClienteF')->name('cliente.fconsulta');
    
    Route::post('/inventario/update','InventarioController@editInventario')->name('inventario.edit');
    Route::post('/inventario/delete','InventarioController@eliminar');

    Route::resource('categoria','CategoriaController');
    Route::post('/categoria/update','CategoriaController@editCategoria')->name('categoria.edit');
    Route::post('/categoria/delete','CategoriaController@eliminar');
});

app/Http/Controllers/SistemaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Cliente;
use App\Inventario;

class SistemaController extends Controller
{
    public function index()
    {
        if(Auth::check())
        {
            if (Auth::user()->tipo == "admin") {
                $cliente = Cliente::orderBy('nombre','desc')->get();
                $producto = Inventario::orderBy('id','desc')->get();
                return view('sistema.venta')
                ->with('cliente',$cliente)
                ->with('productos',$producto);
            } else {
                return view('errors.access');
            }
        }else {
            return view('auth.login');
        }
   
        
    }
}

resources/views/sistema/comprobante.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Nota de venta</title>
   
    <style>

        @page{margin-top: 9mm;}
        .margen{
            width: 190mm;
            height: 125mm;
            position: relative;
            /* border: 1px solid red; */
        }

        img{
            height: 20mm;
            margin-left: 10px;
            margin-top: 12px;
        }

        #datos{
            position: fixed;
            left: 200px;
            top: 10px;
            font-size: 12px;
            margin-top:15px;
        }

        #folio{
            position: absolute;
            top:-12px;
            left: 550px;
        }
        #fo
        {
            font-size: 15px;
        }

        #fe{
            font-size: 12px;
        }

        #fo-num{            
            color:darkred;
        }

        .cliente{
            width: 100%;
            margin-top:10px;
            font-size: 12px;
            border: 1px solid #252525;
            margin-bottom: 10px;
            border-radius: 5px;
        }
        .detventa{
            width: inherit;
            border-collapse: collapse;
        }
        .detventa tbody td {
            border-collapse: collapse;
            padding-top: 5px;
        }
        .divventa{
            width: 100%;
            margin-top: 10px;
        }

        .detventa thead{
            border-bottom: 1px solid #252525;
            text-align: center;
        }

        .detventa tbody{
            text-align: center;
            font-size: 12px;
        }

        .detalles{
            margin-left: 10px;
            font-size: 12px;
        }

        .divt{
            font-weight: bold;
            text-align:right;
        }

        .foot{
            width:190mm;
            position:fixed;
            top: 435px;
            text-align: justify;
            font-size: 10px;
            padding: 5px;
        }

        .letra{
            float: left;
            text-align: center;
            border: 1px solid #252525;
            padding: 5px;
            border-radius: 5px;
            font-size: 11px;
            width: 260px;
        }

        .obv{
            width: 320px;
            float: right;
            margin-top: 10px;
            padding-right: 10px;
            padding-left: 10px;
            font-size: 12px;
            border: 1px solid #252525;
            border-radius: 5px;

        }
        .desc{
            width: 320px;
            padding-right: 10px;
            padding-left: 10px;
            font-size: 12px;
            border: 1px solid #252525;
            border-radius: 5px;
        }

        .det{
            width: 80%;
            font-size: 12px;
            border: 1px solid #252525;
            border-radius: 5px;
        }
    </style>
</head>
<body>
    <div class="margen">

        <div class="header">
                <img src="{{public_path().'/img/logotinta.jpg'}}" alt="">
                <div id="folio">
                    <p>NOTA DE SERVICIO</p>
                <p id="fo">Folio: <span id="fo-num">{{str_pad($servicio->id, 6, '0', STR_PAD_LEFT)}}</span>
                    <br><span id="fe">Fecha: {{$servicio->created_at}}</span>
                </p>
            
                        <p id="datos">3a Norte #724-A entre 6a Y 7a Poniente 
                            <br>Centro Tuxtla Gutierrez, Chiapas. 
                            <br>Correo: mastintatoner@hotmail.com
                            <br>Tel. 961 18 599 59
                        </p>
                </div>
        </div>

        <table class="cliente">
            <tr><td>Nombre: {{$servicio->cliente->nombre}}</td></tr>
            <tr><td>Direccion: {{$servicio->cliente->direccion}}</td></tr>
            <tr><td>Ciudad: {{$servicio->cliente->ciudad}}</td></tr>
            <tr><td>Telefono: {{$servicio->cliente->telefono}}</td></tr>
        </table>

        <div class="det divventa">
            <table class="detalles">
                <tr><td>Tipo de servicio: {{$servicio->tipo}}</td></tr>
                <tr><td>Marca: {{$servicio->marca}}</td></tr>
                <tr><td>Modelo: {{$servicio->modelo}}</td><td>N/S: {{$servicio->serial}}</td></tr>
            </table>
        </div>

        <div class="obv">
                <p>Observaciones:</p>
                <p>@php echo nl2br($servicio->observaciones) @endphp</p>
        </div>
  
        <div class="desc">
            <p>Descripción:</p>
            <p>@php echo nl2br($servicio->descripcion) @endphp</p>
        </div>


    <div class="foot">*Garantía de 30 días presentando su nota. 
        <br>*El cliente es consciente que en las impresoras de tinta puede taparse el cabezal de impresión si no se usa constantemente.
        <br>*Al notificar que el equipo esta listo, si no se recoge después de 15 días no nos haremos resposables del mismo. 
    </div>
</div>
    

</body>
</html>

resources/views/sistema/login.blade.php
<!DOCTYPE html>
<html lang="es">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <meta name="csrf-token" content="{{ csrf_token() }}">
  <title>Recarga T&T</title>
  <!-- Bootstrap core CSS-->
  <link href="{{asset('vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
  <!-- Custom fonts for this template-->
  <link href="{{asset('vendor/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet" type="text/css">
  <!-- Custom styles for this template-->
  <link href="{{asset('css/sb-admin.css')}}" rel="stylesheet">
</head>

<body class="bg-dark">
  <div class="container">
    <div class="card card-login mx-auto mt-5">
      <div class="card-header">Login</div>
      <div class="card-body">
        <form method="POST" action="{{ route('login') }}">
          @csrf

          <div class="form-group">
            <label for="email">Correo</label>
            <input class="form-control" name="email" type="email"  value="{{ old('email') }}" required autofocus >
            @if ($errors->has('email'))
              <span class="invalid-feedback">
                  <strong>{{ $errors->first('email') }}</strong>
              </span>
            @endif
          </div>

          <div class="form-group">
            <label for="password">Contraseña</label>
            <input class="form-control" id="password" name="password" type="password">
            
            @if ($errors->has('password'))
              <span class="invalid-feedback">
                  <strong>{{ $errors->first('password') }}</strong>
              </span>
            @endif
          </div>

          <button class="btn btn-primary btn-block" type="submit" >Login</button>
        </form>

      </div>
    </div>
  </div>
    <!-- Bootstrap core JavaScript-->
    <script src="{{asset('vendor/jquery/jquery.min.js')}}"></script>
    <script src="{{asset('vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
    <!-- Core plugin JavaScript-->
    <script src="{{asset('vendor/jquery-easing/jquery.easing.min.js')}}"></script>
    <!-- Custom scripts for all pages-->
    <script src="{{asset('js/sb-admin.min.js')}}"></script>
</body>

</html>

resources/views/sistema/nota.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Nota de venta</title>
   
    <style>
        @page{margin: 10mm;}

        .margen{
            width: 120mm;
            height: 190mm;
            position: relative;
            margin-left:auto;
        }
        img{
            width: 50mm;
            margin-top: 18px;
        }
        #datos{
            font-size: 10px;
            margin-top:15px;
        }
        #folio{
            position: absolute;
            top:-12px;

            margin-left: 60px;
        }
        #fo
        {
            font-size: 15px;
        }

        #fe{
            font-size: 12px;
        }

        #fo-num{            
            color:darkred;
        }

        .cliente{
            width: 100%;
            margin-top:10px;
            font-size: 13px;
            border: 1px solid #252525;
            border-radius: 5px;
        }
        .detventa{
            width: inherit;
            border-collapse: collapse;
        }
        .detventa tbody td {
            border-collapse: collapse;
            padding-top: 5px;
        }
        .divventa{
            width: 100%;
            height: 330px;
            margin-top: 15px;
        }

        .detventa thead{
            border-bottom: 1px solid #252525;
            text-align: center;
        }

        .detventa tbody{
            text-align: center;
            font-size: 12px;
        }

        .totales{
            padding: 5px;
            border: 1px solid #252525;
            border-radius: 5px;
            width: 160px;
            float: right;
            font-size: 15px;
            

        }

        .divt{
            font-weight: bold;
            text-align:right;
        }

        .foot{
            width:110mm;
            position:absolute;
            bottom: 10px;
            text-align: justify;
            font-size: 12px;
            padding: 5px;
        }

        .letra{
            float: left;
            text-align: center;
            border: 1px solid #252525;
            padding: 5px;
            border-radius: 5px;
            font-size: 11px;
            width: 260px;
        }
    </style>
</head>
<body>
    <div class="margen">

        <div class="header">
                <img src="{{public_path().'/img/logotinta.jpg'}}" alt="">
                <div id="folio">
                    <p>NOTA DE VENTA</p>
                <p id="fo">Folio: <span id="fo-num">{{str_pad($venta->id, 6, '0', STR_PAD_LEFT)}}</span>
                    <br><span id="fe">Fecha: {{$venta->created_at}}</span>
                </p>
            
                        <p id="datos">3a Norte #724-A entre 6a Y 7a Poniente 
                            <br>Col. Centro Tuxtla Gutierrez, Chiapas. 
                            <br>Correo: mastintatoner@hotmail.com
                            <br>Tel. 961 18 599 59
                        </p>
                </div>
        </div>

        <table class="cliente">
            <tr><td>Nombre: {{$venta->cliente->nombre}}</td></tr>
            <tr><td>Direccion: {{$venta->cliente->direccion}}</td></tr>
            <tr><td>Ciudad: {{$venta->cliente->ciudad}}</td></tr>
            <tr><td>Telefono: {{$venta->cliente->telefono}}</td></tr>
        </table>

        <div class="cliente divventa">
        <table class=" detventa">
            <thead >
                <tr>
                    {{-- <th>#</th> --}}
                    <th>Descripción</th>
                    <th>Cantidad</th>
                    <th>Precio</th>
                    <th>Importe</th>
                </tr>
            </thead>
            <tbody >
                @foreach ($venta->inventarios as $item)
                    <tr>
                    {{-- <td>{{$item->id}}</td> --}}
                    <td  style="text-align:left;padding-left:10px;">{{$item->descripcion}}</td>
                    <td>{{$item->pivot->cantidad}}</td>
                    <td>{{number_format($item->preciov, 2)}}</td>
                    <td>{{number_format($item->pivot->importe,2)}}</td>
                    </tr>
                @endforeach

                @foreach ($venta->servicios as $item)
                <tr>
                {{-- <td>{{$item->id}}</td> --}}
                <td  style="text-align:left;padding-left:10px;">{{$item->tipo}}</td>
                <td>{{$item->pivot->cantidad}}</td>
                <td>{{number_format($item->pivot->importe, 2)}}</td>
                <td>{{number_format($item->pivot->importe,2)}}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
  

    <div>
        <p class="letra">{{$letras->convertir($venta->total,'pesos','centavos')}}</p>

        <div class="totales">
                <table>
                    <tr><td class="divt">Subtotal $</td><td>{{number_format($venta->subtotal,2)}}</td></tr>
                    <tr><td class="divt">Descuento $</td><td>{{number_format($venta->descuento,2)}}</td></tr>
                    <tr><td class="divt">Total $</td><td>{{number_format($venta->total,2)}}</td></tr>
                       
                </table>
        </div>
    </div>

    <div class="foot">*Es necesario presentar esta nota para hacer validada la garantía por cualquier detalle o defecto en su articulo.</div>
</div>
    

</body>
</html>

resources/views/sistema/servicio.blade.php
@extends('layouts.sistema')

@section('css')
<link rel="stylesheet" href="{{asset('css/venta.css')}}">
@endsection

@section('js')
<script src="{{asset('js/servicio.js')}}"></script>
@endsection

@section('contenido')
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page"><i class="fa fa-fw  fa-wrench icon"></i> Nuevo servicio</li>
    </ol>
</nav>
<form id="servForm" action="{{route('servicio.store')}}" method="post">   </form>

<div class="w-100 d-flex" id="clientelist">
    <div class="input-group input-group-sm mb-4 d-flex flex-nowrap ">
        <div class="input-group-prepend d-sm-none">
          <span class="input-group-text" id="inputGroup-sizing-sm">Cliente</span>
        </div>

      
        <select id="select-cliente" form="servForm" required  name="cliente" class="w-75" aria-label="Small" aria-describedby="inputGroup-sizing-sm">
            <option></option>
            @foreach ($cliente as $item)
        <option value="{{$item->id}}">{{$item->nombre.' '.$item->apellido}}</option>    
            @endforeach
            
        </select>
        <a class="ml-2" href="#" data-toggle="modal" data-target="#addClienteModal"><i style="font-size:32px;" class="fa fa-fw fa-plus-circle text-danger" ></i></a>
    </div>
            
</div>

    <div id="detCliente" class="">
            <div class="d-flex  flex-wrap flex-xl-nowrap">
                <div class="input-group input-group-sm d-flex flex-nowrap ml-0 mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing-sm">Correo</span>
                    </div>
                    <input id="detCorreo" class="form-control" disabled type="email" name="correo" id="">
                </div>
        
                <div class="input-group input-group-sm d-flex flex-nowrap mb-3 ml-xl-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing-sm">Teléfono</span>
                    </div>
                    <input id="detTelefono" class="form-control" disabled type="text" name="telefono" id="">
                </div>
    
                <div class="input-group input-group-sm d-flex flex-nowrap ml-xl-3 mb-xl-3 mb-md-3 mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing-sm">R.F.C</span>
                    </div>
                    <input id="detRfc" class="form-control" disabled type="text" name="rfc" id="">
                </div>
            </div>
    
            <div class="mt-lg-0 d-flex flex-wrap flex-xl-nowrap">
                <div class="input-group input-group-sm mr-xl-4 mb-3 d-flex flex-nowrap ">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing-sm">Dirección</span>
                    </div>
                    <input id="detDireccion" class="form-control" disabled type="text" name="direccion" id="">
                </div>
        
                <div class="input-group input-group-sm d-flex flex-nowrap mb-3 ">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing-sm">Ciudad</span>
                    </div>
                    <input id="detCiudad" class="form-control" disabled type="text" name="ciudad" id="">
                </div>
            </div>      
        </div>

    <div class="media-sm input-group input-group-sm  mb-4 w-75">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroup-sizing-sm">Tipo de servicio</span>
            </div>
            <input required form="servForm" id="tipo" class="form-control"  type="text" name="tipo">
    </div>

    <div class="d-flex w-75 mb-4  flex-wrap flex-xl-nowrap flex-lg-nowrap flex-md-nowrap media-sm">
        <div class="input-group input-group-sm d-flex flex-nowrap mr-4 media-sm mb-3 mb-lx-0 mb-lg-0 mb-md-0">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroup-sizing-sm">Marca</span>
            </div>
            <input form="servForm" required  class="form-control"  type="text" name="marca">
        </div>

        <div class="input-group input-group-sm d-flex flex-nowrap mr-4 media-sm mb-3 mb-lx-0 mb-lg-0 mb-md-0">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroup-sizing-sm">Modelo</span>
            </div>
            <input required form="servForm" id="modelo" class="form-control" type="text" name="modelo">
        </div>
        <div class="input-group input-group-sm d-flex flex-nowrap ">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroup-sizing-sm">N/S</span>
            </div>
            <input form="servForm" placeholder="(opcional)" id="serial" class="form-control" type="text" name="serial" >
        </div>
    </div>

    <div class="d-flex  flex-wrap flex-xl-nowrap flex-lg-nowrap flex-md-nowrap media-sm  mb-5">
            <div class="input-group input-group-sm d-flex flex-nowrap mr-4 media-sm mb-3 mb-lx-0 mb-lg-0 mb-md-0">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroup-sizing-sm">Falla</span>
                </div>
                <textarea required form="servForm" rows="5" class="form-control" name="descripcion" ></textarea>
            </div>
    
            <div class="input-group input-group-sm d-flex flex-nowrap mr-4 media-sm">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroup-sizing-sm">Observaciones</span>
                </div>
                <textarea required form="servForm" rows="5"  class="form-control"  name="observaciones"></textarea>
            </div>

        </div>
 
        <button id="registrar" type="button" data-toggle="modal" data-target="#ModalConfirm" class="mb-4 btn btn-success btn-lg btn-block"><i class=" fa fa-fw fa-check-circle"></i>Registrar</button>

        <!-- Modal confirmación-->

        <div class="modal fade" id="ModalConfirm" tabindex="-1" role="dialog" aria-labelledby="ModalConfirm" aria-hidden="true">
            <div class="modal-dialog modal-sm">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="">¿Guardar servicio?</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-footer">
                        <button id="addCancel" type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                        <button form="servForm" type="submit" id="guardarServ" class="btn btn-primary">Guardar</button>
                      </div>
                </div>
            </div>
        </div>


<!-- Modal  para nuevo cliente -->
<div class="modal fade" id="addClienteModal" tabindex="-1" role="dialog" aria-labelledby="addClienteModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="">Nuevo cliente</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                <form action="{{route('Cliente.store')}}" id="addCliente" method="post">
                        @csrf
                    <input class="form-control mb-3" type="text" name="nombre" placeholder="Cliente/Empresa*" required id="">
                    <div class="form-group d-flex">
                        <input class="form-control mr-3" placeholder="RFC (opcional)" type="text"  pattern="(^([A-ZÑ&]{3,4}) ?(?:- ?)?(\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\d|3[01])) ?(?:- ?)?([A-Z\d]{2})([A\d])$)" name="rfc" id="">
                        <input class="form-control" placeholder="Correo (opcional)" type="email" name="correo" id="">
                    </div> 
                    <input class="form-control mb-3" placeholder="Direccion (opcional)" type="text" name="direccion" id="">
                    <div class="form-group d-flex">
                        <input class="form-control mr-3" placeholder="Telefono (opcional)" type="text" pattern="(^([\d]{7}|[\d]{10})$)" name="telefono" id="">
                        <input class="form-control" placeholder="Ciudad (opcional)" type="text" name="ciudad" id="">
                    </div> 
                </form>
            </div>
            <div class="modal-footer">
              <button id="addCancel" type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
              <button type="submit" form="addCliente" class="btn btn-primary">Guardar</button>
            </div>
        
          </div>
        </div>
      </div>
@endsection